# Generated by Django 4.1.7 on 2023-03-15 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('dataNascita', models.DateField()),
                ('LuogoNascita', models.CharField(max_length=30)),
                ('dataConseguimento', models.DateField(default=django.utils.timezone.now)),
                ('votazione', models.IntegerField()),
                ('codiceId', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
