# Generated by Django 4.1.7 on 2023-03-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diploma',
            old_name='LuogoNascita',
            new_name='luogoNascita',
        ),
    ]
