# Generated by Django 4.1.7 on 2023-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0003_diploma_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
