# Generated by Django 4.1.7 on 2023-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProject', '0004_alter_diploma_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
